### ISSUE TITLE
Analysis of features in poisson, negative binomial, etc.

### ISSUE THREAD

**Issue by vl237** [dominance-analysis/dominance-analysis#20]
Is there a way to use this library for analysis of feature importance in poisson, negative binomial, etc. distributions(GLM models)?

**Comment by shashank-subex** [comment]
Yes, you can use it for Poisson and Negative Binomial distributions in GLM. Since there are no R-squared defined for GLM, you have to use one of the pseudo R Squared measure. We advise using Mc Fadden's Pseudo R squared but you can use any of the pseudo R-squared measures that we have as part of this package.

**Comment by quintshekhar** [comment]
use Pseudo R Squared measure as in the below example:

dominance_classification=Dominance(data=breast_cancer_data,target='target',objective=0,pseudo_r2="mcfadden")
